# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[],
    datas=[('config.json', '.'), ('*.py', '.')],
    hiddenimports=[
        'json',
        'os',
        'sys',
        'getpass',
        'sqlite3',
        're',
        'hashlib',
        'socket',
        'uuid',
        'platform',
        'secrets',
        'time',
        'datetime',
        'unicodedata',
        'urllib.request',
        'tempfile',
        'PIL',
        'PIL.Image',
        'pymongo',
        'db',
        'auth',
        'posts',
        'social',
        'admin',
        'ascii',
        'level',
        'utils',
        'database_m',
        'database_s',
        'config_loader',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=['matplotlib', 'numpy', 'pandas', 'scipy', 'tkinter', 'IPython', 'notebook', 'pkg_resources'],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='socialnet',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
